name: CI/CD for Go Web Server
on:
  pull_request:
    types: 
    - closed
    branches:
    - master
  push:
    branches:
    - master

jobs:
  # Ga ada test buat sekarang
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Verify dependencies
      run: go mod verify
      
    - name: Build
      run: go build -v ./...
      
  build-docker-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build Docker Image
      run: docker build -t loyalty59/simling:latest .
      
    - name: Push Docker Image to DockerHub
      run: docker push loyalty59/simling:latest
      
  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
          echo ${{ secrets.SSH_PRIVATE_KEY }}
          docker pull loyalty59/simling:latest
          docker stop simling || true
          docker rm simling || true
          docker run -d --name go-cicd -p 3001:3000 --restart always loyalty59/simling:latest
          docker image prune -f